import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import Player from '../components/player'

export default function Home() {

  const [state, setState] = useState({
    ptsPlayer1: 0,
    ptsPlayer1Temp: 0,
    ptsPlayer1List: [0],
    ptsPlayer2: 0,
    ptsPlayer2Temp: 0,
    ptsPlayer2List: [0],
    ptsPlayer3: 0,
    ptsPlayer3Temp: 0,
    ptsPlayer3List: [0],
    ptsPlayer4: 0,
    ptsPlayer4Temp: 0,
    ptsPlayer4List: [0]
  })

  const handleChange = e => {
    setState({
      ...state,
      [e.target.name]: e.target.value,
    })
  }

  const handleClick = e => {
    let copy = {...state};
    copy[e.target.ariaLabel] = +copy[e.target.ariaLabel+'Temp'] + copy[e.target.ariaLabel]
    copy[e.target.ariaLabel+'List'] = [...copy[e.target.ariaLabel+'List'], copy[e.target.ariaLabel]]
    setState(copy)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Player name="Jogador 1"></Player>
        <Player name="Jogador 2"></Player>
        <Player name="Jogador 3"></Player>
        <Player name="Jogador 4"></Player>
      </main>
    </div>
  )
}
